### ISSUE TITLE
Join our Slack chatroom link no longer works

### ISSUE THREAD

**Issue by alokmenghrajani** [openaccounting/oa-server#28]
The [Join our Slack chatroom](https://join.slack.com/t/openaccounting/shared_invite/enQtNDc3NTAyNjYyOTYzLTc0ZjRjMzlhOTg5MmYwNGQxZGQyM2IzZTExZWE0NDFlODRlNGVhZmZiNDkyZDlhODYwZDcyNTQ5ZWJkMDU3N2M) seems to be expired (I get "This link is no longer active").

I would be interested to join your Slack if it's still active.

Specifically, I made [a bunch of Docker files](https://github.com/alokmenghrajani/openaccounting-docker) to make it easier to run the software locally and was wondering if you think it would be helpful to others.

**Comment by pnagurny** [comment]
Hi Alok, can you try the updated link? I think the Docker files would certainly be helpful for people! I could include a link to your project in the README, or if you have suggestions for how to incorporate it into my repo's, let me know.

**Comment by alokmenghrajani** [comment]
The Slack link in the README now works, thanks!

Nit: the Slack link on https://openaccounting.io/source-code hasn't been updated.

For the Docker stuff, you can link to my repo in the README or clone my repo under https://github.com/openaccounting/, whichever you prefer. I picked the same MIT license for the Docker files so there's the same licensing as oa-web and oa-server.

**Comment by pnagurny** [comment]
Great! I updated the other link at https://openaccounting.io/source-code.

I also updated the README.md to link to your docker repository. Thanks again for putting that together.
